version: '2'
 
services:
 
  jenkins:
    container_name: jenkins
    build:
      context: .
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    privileged: true
 
 
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    ports:
      - "8080:80"
      - "8443:443"
      - "8022:22"
    volumes:
      - /etc/gitlab
      - /var/log/gitlab
      - /var/opt/gitlab